# Generated by Django 6.1.1 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topic_options_topic_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='guide_content',
            field=models.TextField(blank=True),
        ),
    ]